### ISSUE TITLE
Is it possible to apply the unofficial patch to Kichikuou Rance when playing via the in-browser implementation?

### ISSUE THREAD

**Issue by sho052** [kichikuou/kichikuou.github.io#2]
This project is so cool. I especially like the added message log from which you can even copy text directly. Thanks a lot for the work in helping to preserve such a timeless classic!

One question I have regarding Kichikuou Rance is that, there are some official patches out there (on [Alice wiki](http://alice.xfu.jp/doku.php?id=%E9%AC%BC%E7%95%9C%E7%8E%8B%E3%83%A9%E3%83%B3%E3%82%B9:%E9%9D%9E%E5%85%AC%E5%BC%8F%E4%BF%AE%E6%AD%A3)) which seem to fix a few miscellaneous bugs of the original game. The [final version](http://alice.xfu.jp/uploader/src/alice0803.zip) seems to contain both 鬼畜王SA.ALD and System39.ain which one would normally copy to the installation folder. I'm wondering if I can apply the patch when I play the game in the browser. Since I am supposed to load the disc images, does it mean I can theoretically modify the contents of the disc image and load the repackaged image?

Or, if I understood it correctly, the WASM implementation is actually an emulator of System35, not System39, and therefore I would not be able to apply any of those unofficial patches to the game if I play online? Would you say the bugs fixed in the unofficial patch are no big deal and I should still be able to enjoy the game normally? That patch is the only thing holding me back from playing Kichikuou Rance (in Japanese) in my browser instead of in a Windows VM without all the quality-of-life improvements :)

**Comment by kichikuou** [comment]
With https://github.com/kichikuou/web/commit/c22988866ed46e0ffa62501670b77c1b52477ac1, now you can apply the patch by dropping `鬼畜王SA.ALD` and `System39.ain` along with the CD image. (If it goes well, you should see "非公式修正39 Ver0.03" in the title screen.) [The emulator](https://github.com/kichikuou/xsystem35-sdl2) implements System3.9, so you should have no problem playing the game. But I can't be sure because you'll be the first person to play the patched version in the browser. :)

Please don't forget to load the patch _every time_ you play the game. If you load data saved in the patched version into the original version (or vice versa), the data will be corrupted.

The unofficial patch fixes many bugs, but critical bugs such as BGM not looping or hanging at the ending do not occur in the browser version, so I think you can still enjoy the game without the patch.

**Comment by sho052** [comment]
This is awesome. Thanks a lot for the quick help! I wonder if you are open to donations/if donation information is available somewhere on the project page so that I could show my appreciation :)

P.S.: I have an idea of adding some shortcuts to the page for the screenshot and message log, for which I might try opening a PR.

**Comment by x-ji** [comment]
As mentioned, opened the PR at https://github.com/kichikuou/web/pull/6 :)

**Comment by kichikuou** [comment]
> This is awesome. Thanks a lot for the quick help! I wonder if you are open to donations/if donation information is available somewhere on the project page so that I could show my appreciation :)

Thank you for offering a donation! I've just created a [buymeacoffee account](https://www.buymeacoffee.com/kichikuou) and made it accessible via the Sponsor button at the project page.
